### ISSUE TITLE
Update jsoncpp to v 1.8.1

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/thirdparty-msvc2015#21]
This avoids bundling a second version for Paraview

**Comment by quantumsteve** [comment]
May we move to `v1.8.1`?  
[VTK bundles v1.8.0](https://github.com/Kitware/VTK/blob/d4e1b9ffc949f2ed9119899d0b5adb76579bf643/ThirdParty/jsoncpp/vtkjsoncpp/json/json.h#L90) and I see no reason to avoid the "minor bug fixes and optimizations" in the latest patch release.
